# Generated by Django 4.2.16 on 2024-09-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ticket_num_adults_ticket_num_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='num_adults',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='num_children',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='num_senior_citizens',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
