# Generated by Django 4.2.16 on 2024-09-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ticket_num_adults_alter_ticket_num_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_no_of_persons',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
