# Generated by Django 4.2.16 on 2024-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ticket_total_no_of_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_phone_num',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
